build:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build 
        --build-arg DB_HOST=$DB_HOST 
        --build-arg DB_NAME=$DB_NAME 
        --build-arg DB_USER=$DB_USER 
        --build-arg DB_PASS=$DB_PASS 
        --build-arg JWT_SECRET=$JWT_SECRET 
        --build-arg JWT_RESET_SECRET=$JWT_RESET_SECRET 
        --build-arg NODE_ENV=$NODE_ENV 
        -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main